jobs:
  include:
    - language: php
      php: '7.2'
      install: composer install
    - language: php
      php: '7.3'
      install: composer install
    - language: php
      php: '7.4'
      install: composer install
    - language: node_js
      node_js: '10'
    - language: node_js
      node_js: '12'
    - language: node_js
      node_js: '13'
    - language: python
      python: '3.5'
      script: nosetests tests/test.py
    - language: python
      python: '3.6'
      script: nosetests tests/test.py
    - language: python
      python: '3.7'
      script: nosetests tests/test.py
    - language: python
      python: '3.8'
      script: nosetests tests/test.py
